# Generated by Django 3.2 on 2021-05-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('hash_block', models.CharField(max_length=500)),
                ('previous_hash', models.CharField(blank=True, max_length=500)),
                ('tx_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.IntegerField()),
            ],
            options={
                'get_latest_by': '-index',
            },
        ),
    ]
