# Generated by Django 3.2 on 2021-05-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_tx', models.CharField(max_length=300)),
                ('in_total', models.DecimalField(decimal_places=8, max_digits=10)),
                ('out_total', models.DecimalField(decimal_places=8, max_digits=10)),
                ('count_txOut', models.IntegerField()),
                ('count_txIn', models.IntegerField()),
                ('status', models.CharField(choices=[(1, 'Unconfirmed'), (2, 'Confirmed')], default=1, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isCoinbase', models.BooleanField(default=False)),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.block')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('hash_txOut', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('spent', models.BooleanField(default=False)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
                ('type_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.currency')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('hash_txIn', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('sigscript', models.CharField(max_length=300)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
                ('txOut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transactionoutput')),
                ('type_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.currency')),
            ],
        ),
    ]
