# Generated by Django 3.2 on 2021-05-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20210502_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionoutput',
            name='type_coin',
            field=models.CharField(max_length=4),
        ),
    ]
