# Generated by Django 3.2 on 2021-05-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transactionoutput_type_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='count_txIn',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='count_txOut',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='in_total',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='out_total',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
