# Generated by Django 3.2 on 2021-05-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20210502_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninput',
            name='type_coin',
            field=models.CharField(max_length=4),
        ),
    ]
