# Generated by Django 3.2 on 2021-05-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transactioninput_type_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioninput',
            name='txOut_id',
        ),
        migrations.AddField(
            model_name='transactionoutput',
            name='hash_txIn',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
