# Generated by Django 3.2 on 2021-05-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(choices=[(1, 'Bitcoin'), (2, 'Ethereum'), (3, 'Litecoin'), (4, 'Dai')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(choices=[(1, 'BTC'), (2, 'ETH'), (3, 'LTC'), (4, 'DAI')], default=1, max_length=50),
        ),
    ]
