# Generated by Django 3.2 on 2021-05-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20210502_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
